package log

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"go.uber.org/zap/zapcore"
	lumberjack "gopkg.in/natefinch/lumberjack.v2"
)

// FilenameEncoder log filename encoder,
// return the full name of the log file.
type FilenameEncoder func() string

// DefaultFilenameEncoder return <process name>-<date>.log.
// Rotates daily based on date (YYYYMMDD format).
func DefaultFilenameEncoder() string {
	return fmt.Sprintf("%s-%s.log", filepath.Base(os.Args[0]), time.Now().Format("20060102"))
}

// HourlyFilenameEncoder returns <process name>-<date>-<hour>.log.
// Rotates hourly based on date and hour (YYYYMMDD-HH format).
func HourlyFilenameEncoder() string {
	return fmt.Sprintf("%s-%s.log", filepath.Base(os.Args[0]), time.Now().Format("20060102-15"))
}

// MinutelyFilenameEncoder returns <process name>-<date>-<hour>-<minute>.log.
// Rotates every minute based on date, hour and minute (YYYYMMDD-HHMM format).
func MinutelyFilenameEncoder() string {
	return fmt.Sprintf("%s-%s.log", filepath.Base(os.Args[0]), time.Now().Format("20060102-1504"))
}

func DefaultTimeEncoder(t time.Time, enc zapcore.PrimitiveArrayEncoder) {
	enc.AppendString(t.Format("2006-01-02 15:04:05.000"))
}

func rollingFileEncoder(opts *Options, encoder FilenameEncoder) (zapcore.WriteSyncer, io.Closer, string) {
	encoded := encoder()
	f := filepath.Join(opts.Output, encoded)
	if opts.DisableRotate {
		fd, err := os.OpenFile(f, os.O_APPEND|os.O_CREATE|os.O_WRONLY|os.O_SYNC, 0o644)
		if err != nil {
			panic(err)
		}
		return zapcore.AddSync(fd), fd, f
	}

	// lumberjack.Logger is already safe for concurrent use, so we don't need to
	// lock it.
	jackl := &lumberjack.Logger{
		Filename:   f,
		MaxSize:    opts.MaxSize,
		MaxAge:     opts.MaxAge,
		MaxBackups: opts.MaxBackups,
	}

	// Wrap lumberjack with time-based rotation checker
	writer := &timeBasedRotateWriter{
		logger:          jackl,
		opts:            opts,
		encoder:         encoder,
		currentFilename: f,
	}

	return zapcore.AddSync(writer), writer, f
}

// timeBasedRotateWriter wraps lumberjack.Logger to support time-based rotation
// It automatically detects the rotation interval based on the filename pattern
// generated by FilenameEncoder
type timeBasedRotateWriter struct {
	logger          *lumberjack.Logger
	opts            *Options
	encoder         FilenameEncoder
	currentFilename string
}

func (w *timeBasedRotateWriter) Write(p []byte) (n int, err error) {
	// Get the current filename from encoder
	encoded := w.encoder()
	newFilename := filepath.Join(w.opts.Output, encoded)

	// Check if filename has changed (indicates time period changed)
	if newFilename != w.currentFilename {
		// Filename changed, need to rotate
		// Update the logger's filename and rotate
		w.logger.Filename = newFilename
		if err := w.logger.Rotate(); err != nil {
			// Log error but continue
			fmt.Fprintf(os.Stderr, "failed to rotate log file: %v\n", err)
		}
		w.currentFilename = newFilename
	}

	return w.logger.Write(p)
}

func (w *timeBasedRotateWriter) Sync() error {
	return w.logger.Close()
}

func (w *timeBasedRotateWriter) Close() error {
	return w.logger.Close()
}
